[RefC] Add 16 and 32 bit access to  base/Data.Buffer .
idris-lang/Idris2 pull request #2609
Opened 2022-08-02 06:00 UTC by seagull-kamome

Some FFI definitions are missing in base/Data.Buffer.
This PR adds 16 and 32 bit access routines.

2022-08-24 12:15 UTC, gallais reviewed
What's the convention behind the `*LE` names? Why is it not uniform?

2022-08-24 12:15 UTC, gallais commented on libs/base/Data/Buffer.idr
> +         "RefC:setBufferWord16LE"
Should this bit `Int16` rather than `Word16`?

2022-10-06 07:58 UTC, CodingCellist requested changes
As gallais suggested, I would also prefer if the `Word` functions were renamed to `UInt` since this describes the C primitive they operate on (unless there is a specific reason for using `Word` instead.

2022-10-06 16:24 UTC, buzden commented
> > What's the convention behind the `*LE` names? Why is it not uniform?
> 
> I suspect it's "Little Endian". It won't matter in 99% of the cases, since most modern machines are LE

Not only machines have set endianness, but also protocols. Say, if one would use `Data.Buffer` to form a network packet where usually Big Endian is used disregarding endianness of the machine where the code is executed, one would definitely want to understand the order bytes are put into the buffer.

2022-11-15 11:15 UTC, merged