Add PreorderReasoning comforts
idris-lang/Idris2 pull request #2778
Opened 2022-11-17 19:09 UTC by crisoagf

PR for #2776

2022-11-17 19:11 UTC, crisoagf commented
FWIW, I compiled all libs with this change and everything seems to work.

2022-11-19 09:05 UTC, ohad commented
Do we really need to use type-classes to do this?
A principle I learned for @gallais: don't search when you can compute.
We know that we need a transitive relation for 2-steps or more, and we know we need a reflexive relation for 0-steps, and we know we don't need anything for 1 step: we already have the proof.

So there's no need to search for the CalcType instance (which might produce ambiguities): we can compute it directly.

Here's the code:
```idris
-- Using a McKinna-McBride view records the depenencies on the type of derivation
-- the additional benefits for pattern-matching aren't used here
public export
data DerivationType : FastDerivation leq x y -> Type where
  TrivialDerivation : DerivationType (|~ x)
  SingleStepDerivation : DerivationType (|~ x <~ step)
  NonTrivialDerivation : DerivationType (der <~ step1 <~ step2)

public export
derivationType : (der : FastDerivation leq x y) -> DerivationType der
derivationType (|~ x) = TrivialDerivation
derivationType (|~ x <~ step) = SingleStepDerivation
derivationType ((z <~ w) <~ step) = NonTrivialDerivation

public export
0 Prerequisite : {0 der : FastDerivation {a = dom} leq x y} -> DerivationType der -> Type
Prerequisite TrivialDerivation = Reflexive dom leq
Prerequisite SingleStepDerivation = ()
Prerequisite NonTrivialDerivation = Transitive dom leq

-- Once we have the prerequisite for transitivity, we have the
-- prerequisite for its inductive predecessor:
public export
inductivePrerequisite : (der : FastDerivation leq x y) ->
  (0 step1 : Step leq y z) -> (0 step2 : Step leq z w) ->
  Prerequisite (derivationType (der <~ step1 <~ step2)) ->
  Prerequisite (derivationType (der <~ step1))
inductivePrerequisite (  |~ y    ) step1 step2 prerequisite = ()
inductivePrerequisite (z <~ step0) step1 step2 prerequisite = prerequisite

public export
preorderPrerequisite : Preorder dom leq => (der : FastDerivation leq x y) -> Prerequisite (derivationType der)
preorderPrerequisite (|~ x) = %search
preorderPrerequisite (|~ x <~ step) = ()
preorderPrerequisite (der <~ step1 <~ step2) = %search

||| The Prerequisite for the derivation:
||| 0-length derivation: Reflexive dom leq
||| 1-length derivation: Unit (no prerequisite)
||| 2 steps of longer: Transitivity
public export
CalcSmart : {0 x : dom} -> {0 y : dom} -> (der : FastDerivation leq x y) ->
  Prerequisite (derivationType der) =>
  x `leq` y
CalcSmart (|~ x) = reflexive
CalcSmart (|~ x <~ y ... step) = step
CalcSmart ((der <~ z ... step1) {x,y}
               <~ w ... step2) @{prereq} =
                CalcSmart (der <~ z ... step1)
                @{inductivePrerequisite der (z ... step1) (w ... step2) prereq}
                  `transitive` step2

public export
CalcWith : Preorder dom leq => {0 x : dom} -> {0 y : dom} -> FastDerivation leq x y -> x `leq` y
CalcWith der = CalcSmart der @{preorderPrerequisite der}
```
This should also work with the existing code base, though I haven't tested it.
It would be good to test also if the `CalcSmart` constructor works instead of your (upcoming?) `TransitiveReasoning` module.
What do you think?

2022-11-19 09:05 UTC, ohad requested changes

2022-11-19 10:08 UTC, gallais commented
Our testing should heavily involve incomplete proofs to ensure we do
not get hard errors when Idris cannot yet compute the `derivationType`
because it gets stuck on a hole.

2022-11-19 11:49 UTC, ohad commented
I agree, though it might work out fine anyway:
+ The current interface (`CalcWith`) requires a `Preorder`, so that's not going to cause new errors.
+ The new interface (`CalcSmart`) computes the interface it needs based on the derivation structure, which ought to be known for incomplete proofs.

But I agree we ought to test these cases.

2022-11-20 15:01 UTC, crisoagf commented on libs/base/Syntax/PreorderReasoning/Generic.idr
> +
No, they are not necessary, I just wasn't aware of how to write `Prerequisite`!

Also `CalcSmart` is a way better name! I'll grab your changes!

2022-11-20 15:04 UTC, crisoagf commented
> (...)
> 
> Do we really need to use type-classes to do this? A principle I learned from @gallais: don't search when you can compute. We know that we need a transitive relation for 2-steps or more, and we know we need a reflexive relation for 0-steps, and we know we don't need anything for 1 step: we already have the proof.
>
No, we don't, I just wasn't aware you could make constraints value-dependent! Grabbing your changes.
 
> 
> This should also work with the existing code base, though I haven't tested it. It would be good to test also if the `CalcSmart` constructor works instead of your (upcoming?) `TransitiveReasoning` module. What do you think?

With `CalcSmart` is there any need for `TransitiveReasoning`? I was thinking of dropping it given the new approach.

2022-11-20 15:28 UTC, crisoagf commented
One other thing that could be done is just add the derivation type to the `FastDerivation` type constructor arguments. That would make transitive derivation and `~=` compatible (with this code if you use `~=` idris can't compute the derivation type, because it would require pattern matching on the `Refl`.

2022-11-25 08:19 UTC, crisoagf commented
@ohad 

> Trawling the stdlib, [here](https://github.com/idris-lang/Idris2/blob/69f680e10a336c4f33414cfd55c13d41b68d735b/libs/contrib/Data/Nat/Division.idr#L271) is one instance where we're proving a strict inequality. It would be good to try and refactor it using the new CalcSmart mechanism and see if it works.

That proof isn't a great example to work on because it goes something like
```
n - 1
< n
== 1*n
<= (1+k) * n -- Note that this has to be a non-strict inequality, because k = 0 is possible
<= (1+k) * n + a -- Again, has to be non-strict, because a=0 is possible
```

Even replacing `n` with `predn + 1`, we still get the same issue.

I did not find any "good" chains of `transitive` to work with (other than some `Fin` proofs, but those don't work for other reasons), but I haven't stopped searching yet.

`minusLtMonotone` was promising, but it has 0 quantity on its arguments, which is not compatible with the `.Generic` module.

2022-11-27 06:19 UTC, ohad commented
`LTE` is a proposition,  so you can implement 
```idris
recall : (0 prf : a `LTE` b) -> a `LTE` b
```
and lead with that

2022-12-24 06:41 UTC, ohad approved these changes

2022-12-24 06:41 UTC, ohad commented on libs/base/Syntax/PreorderReasoning.idr
> +-- For documenting an equality that the compiler knows about but is not trivial to the reader.
```suggestion
||| Use a judgemental equality but is not trivial to the reader.
```

2022-12-24 06:42 UTC, ohad commented
Sorry this has taken so long. Thanks for implementing all the changes --- looks good! I'll merge once tests pass.

2022-12-24 09:27 UTC, ohad commented
The issue with `test-elab` is that they're also using an infix operator `.=>`, but with different fixity precedence/association, and the importing of `PreorderReasoning` interferes with their conventions.

I opened issue #2832 that this kind of overriding ought to at least generate a warning, and @stefan-hoeck has agree to look into how to best change `elab-utils` to work around this issue.

2023-01-06 12:52 UTC, stefan-hoeck commented
This has been fixed at elab-util, so the test should now succeed.

2023-01-13 17:48 UTC, ohad commented
I'm told that to fix the broken test we should upstream changes from `main`:

https://github.com/crisoagf/Idris2/pull/1

2023-02-17 10:35 UTC, gallais commented
It does not look like the elab-utils fix was successful?

2023-02-17 14:52 UTC, stefan-hoeck commented
> It does not look like the elab-utils fix was successful?

I'll have a look.

2023-02-17 14:53 UTC, ohad commented
Does [this PR helps](https://github.com/stefan-hoeck/idris2-elab-util/pull/64)?

2023-02-17 15:07 UTC, stefan-hoeck commented
> Does [this PR helps](https://github.com/stefan-hoeck/idris2-elab-util/pull/64)?

Thanks for this, but I think a more thorough fix is OK. I deprecated the lambda operator an (to the best of my knowledge) removed all its uses from the code base. Please restart the CI tests. elab-util should be fine now.

2023-02-17 15:13 UTC, stefan-hoeck commented
Damn. I'll look again.

2023-02-17 15:21 UTC, stefan-hoeck commented
Sorry for this. Please run again. (Fingers crossed)

2023-02-17 17:46 UTC, ohad commented
Awesome! Thanks everyone, and apologies to @crisoagf for the merge taking so long!

2023-02-17 17:47 UTC, merged