[ elab ] Support more applicative traversals of `TTImp`
idris-lang/Idris2 pull request #3130
Opened 2023-10-31 21:55 UTC by buzden

# Description

I propose to allow a bit more applicable, applicative mapping of `TTImp`s, which generalises existing `mapMTTImp` way.

Proposed way allows you to do, for example, the following. Since traversal goes bottom up, from leaves up to the root, there might be not enough information of whether some transformation should be done, or not. Consider you want some transformation happen, but want to cancel it if some condition happens. You may need an original value at this point. The proposed addition of `mapMMTTImp` (along with existing `mapMTTImp`) allows this:

```idris
record WithOrig a where
  constructor W
  orig : a
  main : Lazy a

Functor WithOrig where
  map f = {orig $= f, main $= f}

Applicative WithOrig where
  pure x = W x x
  W fo fm <*> W xo xm = W (fo xo) (fm xm)

whateverTransformation : TTImp -> TTImp

condTrans : WithOrig TTImp -> WithOrig TTImp
condTrans wo = if cond wo.orig then wo else {main $= whateverTransformation} wo
```

Running `mapMMTTImp condTrans expr`, you have both original **sub**expression and the transformed one inside the `condTrans` function, allowing you to control precisely whether or not any particular change should be done.

## Should this change go in the CHANGELOG?

- [x] If this is a fix, user-facing change, a compiler change, or a new paper
      implementation, I have updated `CHANGELOG.md` (and potentially also
      `CONTRIBUTORS.md`).

2023-11-01 06:02 UTC, buzden commented
I also updated one test to reduce the need of constant updates of its golden value on every standard library change, the second commit is for that.

2023-11-09 14:03 UTC, gallais requested changes
Looks good to me. Can we call it `mapATTImp` instead though?

2023-11-09 15:10 UTC, buzden commented
> Looks good to me. Can we call it `mapATTImp` instead though?

Sure, done.

2023-11-09 15:56 UTC, gallais approved these changes

2023-11-09 22:05 UTC, merged