Add pipeline operators
idris-lang/Idris2 pull request #3284
Opened 2024-05-19 10:54 UTC by observant2

# Description
Adds the pipeline operators `|>` and `<|` known from other functional languages like F# and Elixir.

## Should this change go in the CHANGELOG?

- [x] If this is a fix, user-facing change, a compiler change, or a new paper
      implementation, I have updated [`CHANGELOG_NEXT.md`](https://github.com/idris-lang/Idris2/blob/main/CHANGELOG_NEXT.md) (and potentially also
      `CONTRIBUTORS.md`).

2024-05-19 12:01 UTC, andrevidela commented
Looks like there are some test to fix because now there are two conflicting fixity definitions for `(<|)`

2024-05-24 14:30 UTC, observant2 commented
Unfortunately I'm stuck here. When I execute "tests/idris2/operators/operators001/Test.idr"
with `%hide Prelude.Ops.infixr.(|>)` I still get the errors:
```
1/1: Building Test (Test.idr)
[-Warning: operator fixity is ambiguous, we are picking Prelude.Ops.infixr.(|>) out of :-]
[- - Prelude.Ops.infixr.(|>), precedence level 9-]
[- - Test.infixr.(|>), precedence level 0-]

[-To remove this warning, use `%hide` with the fixity to remove-]
[-For example: %hide Prelude.Ops.infixr.(|>)-]
```
It suggests me to do what I already did.

2024-05-24 16:27 UTC, andrevidela commented
Do the tests run locally? it seems there are still conflicting fixity definitions in the file `Import.idr` for the test `idris2/misc/import009`

2024-05-24 20:26 UTC, observant2 commented
Now they should pass.

2024-05-24 21:43 UTC, observant2 commented
Oh, I forgot, someone commented in Discord:
> shouldn't `(|>)` be `infixl` in the prelude?
> also, I think it would make more sense if both pipeline operators had the same precedence

So should I make |> infixl? If they should get the same precedence, which should it be?

2024-05-25 02:20 UTC, buzden commented
> So should I make |> infixl?

You definitely should. Even example from your docstring shouldn't typecheck if this operator leaves `infixr`.

> If they should get the same precedence, which should it be?

Precedence should be low enough to be able to form the value you are operating on. Again, in your docstring, you are, actually, applying `|>` after a bunch of `::` (which `[a, b c]` desugars to), so `|>` should have a precedence *lower* than that (and now it's very high). I think that 0 for both is rather a good choice.

Maybe you should add the example from your docstring as a test in order to check that what you intended still works.

2024-05-25 06:50 UTC, observant2 commented
Okay, that's a good idea, where should this test go? Is there an existing file where it would fit or should I create a new `operators011` folder?

2024-05-25 08:14 UTC, buzden commented
> Okay, that's a good idea, where should this test go? Is there an existing file where it would fit or should I create a new `operators011` folder?

It should go here, I think:
https://github.com/idris-lang/Idris2/tree/main/tests/prelude

2024-05-25 10:42 UTC, observant2 commented on tests/idris2/operators/operators001/Test.idr
> +%hide Prelude.Ops.infixr.(|>)
Without this line I would still get warnings, although that operator doesn't exist.

2024-06-05 07:49 UTC, gallais requested changes
Please fix the CI errors

2024-06-06 09:59 UTC, gallais approved these changes

2024-06-06 09:59 UTC, merged